### ISSUE TITLE
I can create a device, but cannot grab metadata

### ISSUE THREAD

**Issue by openedhardware** [googleapis/python-iot#207]
#### Environment details

  - OS type and version: Ubuntu 20.04 on Google VM Instance
  - Python version: 3.8.10
  - pip version: `pip --version`21.2.4
  - `google-cloud-iot` version: 
      ```shell
      Name: google-cloud-iot
      Version: 2.2.1
      Summary: Cloud IoT API API client library
      Home-page: https://github.com/googleapis/python-iot
      Author: Google LLC
      Author-email: googleapis-packages@oogle.com
      License: Apache 2.0
      Location: /usr/local/lib/python3.8/dist-packages
      Requires: google-api-core, proto-plus, grpc-google-iam-v1, packaging
      Required-by:
      ```

#### Code example

```python
import io
import os
import sys

from google.cloud import iot_v1
from google.protobuf.field_mask_pb2 import FieldMask
from settings import GCP_PROJECT_ID, GCP_LOCATION, GPC_REG_ID


client = iot_v1.DeviceManagerClient()
registry_path = client.registry_path(GCP_PROJECT_ID, GCP_LOCATION, GPC_REG_ID)


def create_keys(public_key="rsa_public.pem", private_key="rsa_private.pem"):
    os.system(f"openssl genpkey -algorithm RSA -out {private_key} -pkeyopt rsa_keygen_bits:2048")
    os.system(f"openssl rsa -in {private_key} -pubout -out {public_key}")


def create_device(device_id, public_key="rsa_public.pem"):

    with io.open(public_key) as f:
        certificate = f.read()

    # Note: You can have multiple credentials associated with a device.
    device_template = {
        "id": device_id,
        "credentials": [
            {
                "public_key": {
                    "format": iot_v1.PublicKeyFormat.RSA_PEM,
                    "key": certificate,
                }
            }
        ],
    }
    return client.create_device(request={"parent": registry_path, "device": device_template})


def get_device_details():
    field_mask = FieldMask(
        paths=[
            "id",
            "name",
            "num_id",
            "credentials",
            "last_heartbeat_time",
            "last_event_time",
            "last_state_time",
            "last_config_ack_time",
            "last_config_send_time",
            "blocked",
            "last_error_time",
            "last_error_status",
            "config",
            "state",
            "log_level",
            "metadata",
            "gateway_config",
        ]
    )
    devices = list(client.list_devices(request={"parent": registry_path, "field_mask": field_mask}))
    return devices


def get_device_metadata(device_id):
    field_mask = FieldMask(
        paths=[
            "id",
            "name",
            "num_id",
            "credentials",
            "last_heartbeat_time",
            "last_event_time",
            "last_state_time",
            "last_config_ack_time",
            "last_config_send_time",
            "blocked",
            "last_error_time",
            "last_error_status",
            "config",
            "state",
            "log_level",
            "metadata",
            "gateway_config",
        ]
    )

    device = client.get_device(request={"name": device_id, "field_mask": field_mask})

    print("Id : {}".format(device.id))
    print("Name : {}".format(device.name))
    print("Credentials:")

    if device.credentials is not None:
        for credential in device.credentials:
            key_info = credential.public_key
            print("\tcertificate: \n{}".format(key_info.key))
            if key_info.format == 4:
                key_format = "ES256_X509_PEM"
            elif key_info.format == 3:
                key_format = "RSA_PEM"
            elif key_info.format == 2:
                key_format = "ES256_PEM"
            elif key_info.format == 1:
                key_format = "RSA_X509_PEM"
            else:
                key_format = "UNSPECIFIED_PUBLIC_KEY_FORMAT"
            print("\tformat : {}".format(key_format))
            print("\texpiration: {}".format(credential.expiration_time))

    print("Config:")
    print("\tdata: {}".format(device.config.binary_data))
    print("\tversion: {}".format(device.config.version))
    print("\tcloudUpdateTime: {}".format(device.config.cloud_update_time))

    return device


if __name__ == '__main__':

    create_keys(public_key='/tmp/rsa_public.pem', private_key='/tmp/rsa_private.pem')
    d = create_device(device_id='sample_device', public_key='/tmp/rsa_public.pem')
    print(d)
    print(get_device_metadata(device_id='sample_device'))

```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "The caller does not have permission"
        debug_error_string = "{"created":"@1634803450.729548399","description":"Error received from peer ipv4:209.85.145.95:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"The caller does not have permission","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "utils/google_iot.py", line 149, in <module>
    print(get_device_metadata(device_id='sample_device'))
  File "utils/google_iot.py", line 95, in get_device_metadata
    device = client.get_device(request={"name": device_id, "field_mask": field_mask})
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/iot_v1/services/device_manager/client.py", line 898, in get_device
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/gapic_v1/method.py", line 142, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @codepriestz,
Please could you take a look?

**Comment by joeklemm** [comment]
Can you please make sure when calling 'client.get_device',  'name' contains a well formatted device identifier?
It seems in the sample only device name is passed instead of a full path.
