### ISSUE TITLE
Cloud IoT Manager example does not work in py2 or py3

### ISSUE THREAD

**Issue by charbull** [googleapis/python-iot#255]
Hi, 

I am trying to follow this example:
https://github.com/googleapis/python-iot/blob/main/samples/api-client/manager/manager.py

I am running this in cloud shell:

```
python manager.py --project_id=MY-PORJECT --cloud_region=us-central1 --service_account_json=foo.json list-registries
```

```
 File "manager.py", line 296
    parent = f"projects/{project_id}/locations/{cloud_region}"
 SyntaxError: invalid syntax                             
```

and with python3:
```
Traceback (most recent call last):
  File "manager.py", line 38, in <module>
    from google.cloud import iot_v1
ImportError: cannot import name 'iot_v1' from 'google.cloud' (unknown location)
```

**Comment by parthea** [comment]
@codepriestz Please could you take a look?

**Comment by charbull** [comment]
Friendly ping :)
